steps:
  - task: HashiCorpTerraformTaskV1@0
    displayName: 'Terraform Apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(projectRoot)/terraform/environments/test'
      environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
      problematicString: 'This is a quoted scalar with some problem'
      anotherInput: 'Another value'