name: Azure DevOps Pipeline

trigger:
  branches:
    exclude:
      - '*'

pr:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.8'
  azureServiceConnection: 'cd1807-Project-Ensuring-Quality-Releases'
  projectRoot: '$(Build.SourcesDirectory)'
  environmentName: 'test'
  backendResourceGroup: 'AzureDevOps'
  backendStorageAccountName: 'tfstate281845088'
  backendContainerName: 'tfstate'
  backendKey: 'test.terraform.tfstate'

stages:
  - stage: Build
    jobs:
      - job: BuildInfrastructure
        strategy:
          maxParallel: 1  # Set the maximum parallelism to 1
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true
              architecture: 'x64'

          - script: |
              echo "Python version: $(python --version)"
            displayName: 'Check Python version'

          - task: TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.2.9'

          - script: 'echo "Terraform version: $(terraform --version)"'
            displayName: 'Check Terraform version'

          - script: 'ls -R'
            displayName: 'List Files in Repository'

          - script: |
              terraform init -backend-config="resource_group_name=$(backendResourceGroup)" -backend-config="storage_account_name=$(backendStorageAccountName)" -backend-config="container_name=$(backendContainerName)" -backend-config="key=$(backendKey)" $(projectRoot)/terraform/environments/$(environmentName)
            displayName: 'Terraform Init'

          - script: 'terraform validate $(projectRoot)/terraform/environments/$(environmentName)'
            displayName: 'Terraform Validate'

          - script: |
              terraform apply -auto-approve $(projectRoot)/terraform/environments/$(environmentName)
            displayName: 'Terraform Apply'

  - stage: Destroy
    jobs:
      - job: DestroyInfrastructure
        strategy:
          maxParallel: 1  # Set the maximum parallelism to 1
        steps:
          - script: |
              terraform destroy -auto-approve $(projectRoot)/terraform/environments/$(environmentName)
            displayName: 'Terraform Destroy'